protected/controllers/ParserController.php
<?php

Yii::setPathOfAlias('vendor', __DIR__ . '/../vendor');
require_once Yii::getPathOfAlias('vendor') . '/phpQuery/phpQuery.php';

class ParserController extends Controller {
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/column2';


/**
* Lists all models.
*/
public function actionIndex() {
    set_time_limit (0);
    $model=new News;
    $this->performAjaxValidation($model);

    $data["model"] = $model;
    $this->render('index', $data);
}

/**
 * Lists all models.
 */
public function actionBeginAjax() {
    set_time_limit (0);
    $model=new News;
    $countNews = isset($_POST['News']['countNews']) ? $_POST['News']['countNews'] : 0;

    $data = array();
    if ($model->launchParser($countNews)) {
        $data['message'] = "Парсинг успешно завершен";
    }

    $data['model'] = $model;
    $this->renderPartial('_ajaxContent', $data, false, true);
}

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id) {
    $model=News::model()->findByPk($id);
    if ($model===null) {
        throw new CHttpException(404,'The requested page does not exist.');
    }

    return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model) {
    if (isset($_POST['ajax']) && $_POST['ajax']==='begin-parse') {
        echo CActiveForm::validate($model);
        Yii::app()->end();
    }
}

/**
 * Обработка ошибок
 */
public function actionError()
{
    if ($error=Yii::app()->errorHandler->error)
    {
        if (Yii::app()->request->isAjaxRequest)
            echo $error['message'];
        else
            $this->render('error', $error);
    }
}

}

protected/controllers/ReportController.php
<?php

class ReportController extends Controller {
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/column2';

/**
 * Регистрируем js-скрипты
 * @param CAction $action
 * @return bool
 */
public function beforeAction($action) {
    if (parent::beforeAction($action)) {
        $cs = Yii::app()->getClientScript();
        $cs->registerScriptFile('/js/script.js');
        return true;
    }
    return false;
}


/**
* Displays a particular model.
* @param integer $id the ID of the model to be displayed
*/
public function actionView($id) {
    $reportModel = Reports::model()->findByPk($id);

    if ($reportModel->type == 'word') {
        $type = 'Words';
        $attr = 'word';
        $wordsLetterModel = new Words();
    } else {
        $cs = Yii::app()->getClientScript();
        $cs->registerScriptFile('/js/jqplot/excanvas.min.js', CClientScript::POS_HEAD, array('media' => 'lt IE 9'));
        $cs->registerScriptFile('/js/jqplot/jquery.jqplot.min.js');
        $cs->registerCssFile('/js/jqplot/jquery.jqplot.min.css');
        $cs->registerScriptFile('/js/jqplot/plugins/jqplot.barRenderer.min.js');
        $cs->registerScriptFile('/js/jqplot/plugins/jqplot.pointLabels.min.js');
        $cs->registerScriptFile('/js/jqplot/plugins/jqplot.categoryAxisRenderer.min.js');

        $this->layout = "//layouts/column1";
        $wordsLetterModel = new Letters();
        $type = 'Letters';
        $attr = 'letter';
        $lettersArray = $wordsLetterModel->findAllByAttributes(array('reportId' => $id, ));

        $letters = array();
        $frequency = array();
        foreach($lettersArray as $letter) {
            $letters[] = $letter->letter;
            $frequency[] = $letter->frequency;
        }
    }

    $wordsLetterModel->unsetAttributes(); // clear any default values
    if (isset($_GET[$type])) {
        $wordsLetterModel->attributes = $_GET[$type];
    }

    $criteria=new CDbCriteria;
    $criteria->compare('reportId',$id);
    $criteria->compare($attr, $wordsLetterModel->$attr, true);
    $criteria->compare('frequency', $wordsLetterModel->frequency);

    $data = array(
        'wordsProvider' => new CActiveDataProvider($wordsLetterModel, array(
                'criteria'=>$criteria,
                'pagination' => array('pageSize' => 20,),
                'sort' => array(
                    'attributes'=>array($attr, 'frequency'),
                ),
            )
        ),
        'model' => $this->loadModel($id),
        'wordsLetterModel' => $wordsLetterModel,
        'attr' => $attr,
        'letters' => isset($letters) ? $letters : 0,
        'frequency' =>  isset($frequency) ? $frequency : 0,
    );

    $this->render('view',$data);
}

/**
* Lists all models.
*/
public function actionIndex() {
    $modelReports = new Reports();
    $dataProvider=new CActiveDataProvider($modelReports, array('pagination' => array('pageSize' => 20,),));
    $this->render('index',array(
            'dataProvider'=>$dataProvider,
        )
    );
}

/**
 * Создание отчета по частоте встречаемости букв
 */
public function actionLetters() {
    set_time_limit (0);
    $modelReports = new Reports();
    $this->performAjaxValidation($modelReports);

    if (isset($_POST['Reports'])) {
        $start = microtime(true);

        $listNews = isset($_POST['Reports']['listNews']) ? $_POST['Reports']['listNews'] : 0;

        $_POST['Reports']['listNews'] = isset($_POST['Reports']['listNews']) ? json_encode($_POST['Reports']['listNews']): 0;
        $modelReports->attributes=$_POST['Reports'];

        $result = $modelReports->createLetterSReport($listNews);
        $time = microtime(true) - $start;

        if( $result ) {
            Yii::app()->user->setFlash('successReportCreated','<div class="alert alert-success">Отчет <a href="/report/view/id/'
                . $modelReports->id . '" class="alert-link">'
                . $modelReports->name . '</a> успешно создан. Время генерации - '
                . number_format($time,5) . ' секунд!</div>');
        }
    }

    $data = array(
        'model' => new News('search'),
        'modelReports' => new Reports('search'),
    );
    $this->render('letters',$data);
}

/**
* Создание отчета по частоте встречаемости слов
*/
public function actionWords() {
    set_time_limit (0);
    $modelReports = new Reports();
    $this->performAjaxValidation($modelReports);

    if (isset($_POST['Reports'])) {
        $start = microtime(true); // время начала генерации отчета

        $listNews = isset($_POST['Reports']['listNews']) ? $_POST['Reports']['listNews'] : 0;
        $_POST['Reports']['listNews'] = isset($_POST['Reports']['listNews']) ? json_encode($_POST['Reports']['listNews']): 0;
        $modelReports->attributes=$_POST['Reports'];

        $result = $modelReports->createWordsReport($listNews);

        $time = microtime(true) - $start; // общее время генерации отчета

        if($result) {
            Yii::app()->user->setFlash('successReportCreated','<div class="alert alert-success">Отчет <a href="/report/view/id/'
                . $modelReports->id . '" class="alert-link">'
                . $modelReports->name . '</a> успешно создан. Время генерации - '
                . number_format($time,5) . ' секунд!</div>');
        }
    }

    $model=new News('search');
    $model->unsetAttributes();  // clear any default values
    if (isset($_GET['Reports'])) {
        $model->attributes=$_GET['Reports'];
    }

    $modelReports=new Reports('search');
    $this->render('words',array(
    'model'=>$model,
    'modelReports'=>$modelReports,
    ));
}

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id) {
    $model = Reports::model()->findByPk($id);
    if ($model===null) {
        throw new CHttpException(404,'The requested page does not exist.');
    }

    return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model) {
    if (isset($_POST['ajax']) && $_POST['ajax']==='reports-form') {
        echo CActiveForm::validate($model);
        Yii::app()->end();
    }
}

}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
    <div class="span-19">
        <div id="content">
            <?php echo $content; ?>
        </div>
        <!-- content -->
    </div>
    <div class="span last">
        <div id="sidebar">
            <?php
            $this->widget('bootstrap.widgets.TbMenu', array('type' => 'list', 'items' => $this->menu,));
            ?>
        </div>
        <!-- sidebar -->
    </div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="language" content="en"/>

    <!-- blueprint CSS framework -->
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css"
          media="screen, projection"/>

    <!--[if lt IE 8]>
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css"
          media="screen, projection"/>
    <![endif]-->

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css"/>

    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

    <!-- mainmenu -->
    <?php $this->widget(
        'bootstrap.widgets.TbNavbar',
        array(
            'brand' => CHtml::encode(Yii::app()->name),
            'fixed' => false,
            'items' => array(
                array(
                    'class' => 'bootstrap.widgets.TbMenu',
                    'items' => array(
                        array('label' => 'Парсер', 'url' => array('/parser/index')),
                        array('label' => 'Отчеты', 'url' => array('/report/index')),
                    )
                )
            )
        )
    ); ?>
    <!-- mainmenu -->

    <?php if (isset($this->breadcrumbs)): ?>
        <?php $this->widget('bootstrap.widgets.TbBreadcrumbs', array(
            'links' => $this->breadcrumbs,
            'homeLink' => CHtml::link(CHtml::encode(Yii::app()->name), Yii::app()->homeUrl)
        )); ?><!-- breadcrumbs -->
    <?php endif ?>

    <?php echo $content; ?>

    <div class="clear"></div>

    <div class="well" id="footer">
        Copyright &copy; <?php echo date('Y'); ?> LightSoft.<br/>
        Все права защищены.<br/>
    </div>
    <!-- footer -->

</div>
<!-- page -->

</body>
</html>